### ISSUE TITLE
Fails on Benchmark_Bip32Derive()

### ISSUE THREAD

**Issue by Geograph-us** [fixmycrypto/FixMyCrypto#1]
In derive path the ExtKey OpenCL version is not equal to the CPU version on RTX 2080 Driver Version: 546.01 CUDA Version: 12.3
`FixMyCrypto.exe -opencl`
```
FixMyCrypto Version 3.0.2.0
OpenCL Supported Platforms & Devices:
+----------------+----------------------------+---------------+--------------+-----+
| Platform       | Device                     | Global Memory | Local Memory | CUs |
+----------------+----------------------------+---------------+--------------+-----+
| 0: NVIDIA CUDA | 0: NVIDIA GeForce RTX 2080 | 8 GiB         | 48 KiB       | 46  |
+----------------+----------------------------+---------------+--------------+-----+

Benchmarking devices...
Selected device (0, 0): NVIDIA GeForce RTX 2080 (NVIDIA Corporation)
Benchmark OpenCL phrases...
Compiling OpenCL scripts (keylen=64 phraseLen=12)...
OpenCL Compiled
Benchmark_Pbkdf2() phrases P:0 D:0 cputime=1174 ocltime=259 badcount=0
CPU phrases/s: 3489
P:0 D:0 phrases/s: 15815
Benchmark OpenCL passphrases...
Benchmark_Pbkdf2() P:0 D:0 passphrases cputime=1103 ocltime=164 badcount=0
CPU passphrases/s: 3714
P:0 D:0 passphrases/s: 24976
Benchmark_Bip32Derive(0)
SK0 OCL b8bd82e7e81b1fd13d9fb033e5f56fc0c94c89dbe2a98b2368e9e00d954a6442 != ExtKey ab1852b95f9fc85875815821aa651e6008bf79c694a839395ab872ea5da6676e
CC0 OCL 1046d6461c6112394e14612244659077e7728ffc2c16963151e1a03d9bc61083 != ExtKey 973bfa8ece3db76f40de17c36ac5e1958bb5fa113324a95e02a6889bb9e97c4e
SK1 OCL aa19576f7eb6d5ce54731d000a3ff5b865c1f57d3d1d424bfc2bca8cc11bb329 != ExtKey 14e13eb0213dbf0c230b8be74c873379db85a7ae5a0e1d83418224edd3141749
CC1 OCL c7fad25db55b6cd638a5502b27aebb31d222dbbee5ebcba6220171ad9552de85 != ExtKey 7403aecb740be50effc404f2d6ce0180287ce66c30e8dce569b0e3c3b7f6d199
SK6 OCL 1ae8d82cd02f9eeb54bec70da6858b8b8c81524b75af315fc1439914d88e507b != ExtKey 4bcc4c788d15f06e83cb106628d468b309a797ff994f7194975912012e01e880
CC6 OCL ae92c035339bd4122452e05870804c2f45f9e9907f332a5e1d5649f265020e82 != ExtKey 45e49f8e16725893c122f802b0546ecabfcc799f644a42c56801064748e44f17
SK7 OCL 0a67dcfb1ab973bbf3b93ff42c17dcde4d8c8c7e22f3593234a7aff49ba1696b != ExtKey f529f50269a898ca2033ac4be908d32551bcb1eb0f7e94462d2a6579cea55208
CC7 OCL 862be2aee98e81b64a2abcf0273bae461cecf430eebe3bc1ad32142f94ea35a8 != ExtKey 150d2ab5c79824c73d0ffeb00fa46143c7b4b18854f231f3439ad70af5c2c0b3
SK8 OCL a655ffa6145b68fcd7b6e87acefae913e9ab88e2f2e88de516bbc834f412100a != ExtKey db80da9a0a3f18f365e8f9be81f01ec1c06aee500513403e24dd12d8c3bd4e12
CC8 OCL d4545478a4f9ccc2b57d1d04c4892d39c1120270fdadcf02ecd1a2efc4203e65 != ExtKey f26420d873076c9165363ca3f1687a78a1466fd84f538cd3af4c97f735a71aed
SK10 OCL f2c2e78db83ea8607e47e3a61ee2131de6fa8c650aef3b7f378dacbc1caa6975 != ExtKey a1051f0ac205c9989f382d5fc2c2da67d68cb5da222c91efd8ef84830f2d5794
CC10 OCL 07e17c1af9a3ea2946c94ff514cf51a7b79f24ee6388ad807424a6a56770d5eb != ExtKey 7f675abc1e010a9cc2729213dec06c43b4067ee6942cf738b9b3aa6dd2f0aed5
...
SK4094 OCL 6d110839fbc42158ef3dd050c782356df5cf9953fac28693661a2e17be970243 != ExtKey e88f575270dfacde42b89dcd7eb3af399d3fb0eb5773e228987230d3ca51fb10
CC4094 OCL 18767b672cbafd57427cafc2a4b586f12ccfc09ac87334b82879d784ee3f4de9 != ExtKey f1723e256f9fbc67d0bfee213503632f1f53a25fdc225c3a4d8b7a892b9d1549
Benchmark_Bip32Derive(0) P:0 D:0 cputime=531 ocltime=76 badkey=2062 badcc=2062
Unhandled exception. System.Exception: bad results in Benchmark_Bip32Derive()
   at FixMyCrypto.OpenCL.Benchmark_Bip32Derive(UInt32 path, Int32 count, Dictionary`2 results) in FixMyCrypto-main\src\OpenCL.cs:line 615
   at FixMyCrypto.OpenCL.BenchmarkDevices(Int32 count) in FixMyCrypto-main\src\OpenCL.cs:line 136
   at FixMyCrypto.FixMyCrypto.Main(String[] args) in FixMyCrypto-main\src\Main.cs:line 36
kernelsRunning=0

```

**Comment by fixmycrypto** [comment]
I've seen this happen before when a driver update caused some OpenCL calculations to come out wrong, so I'll have to investigate and might have to switch back to a slower algorithm.

**Comment by fixmycrypto** [comment]
@Geograph-us I just posted a new release which removed the OpenCL code which wasn't working. Everything should be working now, but some solving will be slower than before, please let me know if you run into any problems.
